on: pull_request
name: FBDistribution
jobs:
  test:
    name: FB
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: |
          cd Fridge
          xcodebuild clean test -project Fridge.xcodeproj -scheme Fridge -destination 'platform=iOS Simulator,OS=12.2,name=iPhone X' CODE_SIGN_IDENTITY="" CODE_SIGNING_REQUIRED=NO ONLY_ACTIVE_ARCH=NO
      
        # env: 
         # destination: ${{ matrix.destination }}
