on: pull_request
name: FBDistribution
jobs:
  test:
    name: FB
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@master
      - name: Build and test
        run: xcodebuild -project Fridge.xcodeproj \
                     
                       clean archive \
                        -configuration release \
                        -sdk iphoneos 
                        -archivePath Fridge.xcarchive
